# Generated by Django 3.2.11 on 2022-01-21 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_count', models.IntegerField(verbose_name='Ilość posiłków')),
                ('calories', models.CharField(max_length=45, verbose_name='Kalorie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Dieta',
                'verbose_name_plural': 'Diety',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_current', models.IntegerField(verbose_name='Aktualna waga')),
                ('height', models.IntegerField(verbose_name='Wzrost')),
                ('age', models.IntegerField(verbose_name='Wiek')),
                ('sex', models.TextField(choices=[('male', 'Mężczyzna'), ('female', 'Kobieta'), ('other', 'Inna')], default='other', max_length=9, verbose_name='Płeć')),
                ('weight_target', models.IntegerField(verbose_name='Waga docelowa')),
                ('physical_activity', models.CharField(max_length=1000, verbose_name='Aktywność fizyczna')),
                ('weight_week_loss', models.IntegerField(verbose_name='Tygodniowa strata wagi')),
                ('allergies', models.CharField(max_length=1000, verbose_name='Alergie')),
                ('illnesses', models.CharField(max_length=1000, verbose_name='Choroby')),
            ],
            options={
                'verbose_name': 'Szczegóły użytkownika',
                'verbose_name_plural': 'Szczegóły użytkownika',
            },
        ),
        migrations.CreateModel(
            name='Vitamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('value', models.FloatField(verbose_name='Ilość')),
            ],
            options={
                'verbose_name': 'Witamina',
                'verbose_name_plural': 'Witaminy',
            },
        ),
        migrations.CreateModel(
            name='WaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Ilość')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Zużycie wody',
                'verbose_name_plural': 'Zużycia wody',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField(verbose_name='Kalorie')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nazwa produktu')),
                ('diet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet_app.diet', verbose_name='Dieta')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
        migrations.CreateModel(
            name='Nutritionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account', models.IntegerField(verbose_name='Konto bankowe')),
                ('competence_proof', models.FileField(upload_to='competence/', verbose_name='Potwierdzenie kompetencji')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Dietetyk',
                'verbose_name_plural': 'Dietetycy',
            },
        ),
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbohydrate', models.IntegerField(verbose_name='Węglowodany')),
                ('proteins', models.IntegerField(verbose_name='Białko')),
                ('total_fat', models.IntegerField(verbose_name='Tłuszcze')),
                ('saturated_fat', models.IntegerField(verbose_name='Tłuszcze nasycone')),
                ('sugars', models.IntegerField(verbose_name='Cukry')),
                ('fibers', models.IntegerField(verbose_name='Błonnik')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet_app.product', verbose_name='Produkt')),
                ('vitamins', models.ManyToManyField(blank=True, default=None, to='diet_app.Vitamin', verbose_name='Witaminy')),
            ],
            options={
                'verbose_name': 'Wartości odżywcze',
                'verbose_name_plural': 'Wartości odżywcze',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Klient')),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klienci',
            },
        ),
    ]
