# Generated by Django 3.2.11 on 2022-01-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='days',
            field=models.PositiveIntegerField(default=0, verbose_name='Dni'),
        ),
    ]
