# Generated by Django 3.2.11 on 2022-01-22 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet_app', '0004_diet_name_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
