# Generated by Django 3.2.11 on 2022-01-22 19:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet_app', '0005_alter_diet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_meals', models.TextField(verbose_name='Dzienne posiłki')),
                ('day', models.DateField(default=datetime.date.today, verbose_name='Dzień diety')),
                ('diet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet_app.diet', verbose_name='Dieta')),
            ],
            options={
                'verbose_name': 'Dzień diety',
                'verbose_name_plural': 'Dni diety',
            },
        ),
    ]
