# Generated by Django 3.2.11 on 2022-01-25 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet_app', '0009_auto_20220125_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Dietetyk', 'verbose_name_plural': 'Dietetycy'},
        ),
        migrations.AlterModelOptions(
            name='nutritionist',
            options={},
        ),
        migrations.AddField(
            model_name='diet',
            name='nutritionist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet_app.nutritionist', verbose_name='Dietetyk'),
        ),
    ]
