# Generated by Django 3.2.11 on 2022-01-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet_app', '0010_auto_20220125_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Klient', 'verbose_name_plural': 'Klienci'},
        ),
        migrations.AlterModelOptions(
            name='nutritionist',
            options={'verbose_name': 'Dietetyk', 'verbose_name_plural': 'Dietetycy'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='diet',
        ),
        migrations.AddField(
            model_name='product',
            name='diet_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet_app.dietday', verbose_name='Dzień diety'),
        ),
    ]
