# Generated by Django 3.2.11 on 2022-01-26 21:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet_app', '0012_auto_20220126_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultations',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 26, 22, 25, 0, 584515), verbose_name='Godzina'),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet_app.product', verbose_name='Produkt'),
        ),
        migrations.RemoveField(
            model_name='nutrients',
            name='vitamins',
        ),
        migrations.AddField(
            model_name='nutrients',
            name='vitamins',
            field=models.TextField(blank=True, null=True, verbose_name='Witaminy'),
        ),
        migrations.DeleteModel(
            name='Vitamin',
        ),
    ]
