# Generated by Django 3.2.11 on 2022-01-26 21:32

import diet_app.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet_app', '0013_auto_20220126_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='date',
            field=models.DateField(validators=[diet_app.utils.present_or_future_date], verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='time',
            field=models.TimeField(verbose_name='Godzina'),
        ),
    ]
