# Generated by Django 3.2.11 on 2022-01-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_app', '0014_auto_20220126_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultations',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Zaakceptowane'),
        ),
    ]
