# Generated by Django 3.2.11 on 2022-01-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220125_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_nutritionist',
            field=models.BooleanField(default=False, verbose_name='Czy dietetyk'),
        ),
    ]
